name: nnUnet
channels:
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - dicom2nifti
  - scikit-image
  - medpy
  - scipy
  - numpy
  - SimpleITK
  - pandas
  - requests
  - nibabel 
  - tifffile 
  - matplotlib
  - pip
  - pip:
    - torch
    - sklearn
    - batchgenerators
    - nnunet
