name: nnUnet
channels:
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - dicom2nifti
  - scikit-image>=0.14
  - medpy
  - scipy
  - numpy
  - SimpleITK
  - pandas
  - requests
  - nibabel 
  - tifffile 
  - matplotlib
  - pip
  - pip:
    - torch>1.10.0
    - sklearn
    - batchgenerators>=0.23
    - nnunet
    - git+https://github.com/FabianIsensee/hiddenlayer.git@more_plotted_details#egg=hiddenlayer